
	      /*This file is automatically generated */
	      package it.unisa.javat;
	          
	      public class VersionBuild {
	        static final public String buildnum = "874";
	        static final public String builduser = "alex8";
	        static final public String builddate = "22-12-2021 11:30:53";  
	      }
	      