
	      /*This file is automatically generated */
	      package it.unisa.javat;
	          
	      public class VersionBuild {
	        static final public String buildnum = "875";
	        static final public String builduser = "alex8";
	        static final public String builddate = "22-12-2021 13:44:30";  
	      }
	      